services:
  firewatch:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    secrets:
      - pgp_public_key
    restart: unless-stopped

secrets:
  pgp_public_key:
    file: ./pubkey.asc
